### ISSUE TITLE
How to caculate bpp

### ISSUE THREAD

**Issue by chouqin3** [alexandru-dinu/cae#12]
Thank you for sharing. I have a question, how to compute bit rate according to GSM. I cannot find in the provided code.  @alexandru-dinu 

Good luck.

**Comment by alexandru-dinu** [comment]
Hello, @chouqin3,

The code doesn't not directly implements the models in the papers, but rather the models are just inspired from Lucas' paper. There's no Gaussian Scale Mixtures implementation at the moment.
