### ISSUE TITLE
Entropy coding?

### ISSUE THREAD

**Issue by logodeeplearning** [alexandru-dinu/cae#2]
thanks for open sourcing your code. But I was wondering where is the part about entropy coding (as used in the paper). How were you able to achieve the low compression ratios without entropy coding?

thanks!

**Comment by alexandru-dinu** [comment]
Hello,

In this initial approach, I have not used entropy coding (as in the paper). The latent representation (i.e. encoded image) is binary. For example, for the `model_ae_conv_32x32x32_zero_pad_bin` model, the latent shape is a 32x32x32 binary tensor, encoding one of the 60 patches of the image.

Therefore, `compressed_size = 60 * 32*32*32 / 8 / 1024 = 240KB`.
In general, `compressed_size = num_patches * latent_size / 8` will give you the size in bytes.

**Comment by alexandru-dinu** [comment]
I have yet to brush-up the project and write proper documentation. Hopefully it will be done by the end of the year.

**Comment by alexandru-dinu** [comment]
Closing this, main issue thread: #6
