### ISSUE TITLE
How to control the degree of image distortion and bitstream size in your code

### ISSUE THREAD

**Issue by JXH-SHU** [alexandru-dinu/cae#22]

**Comment by alexandru-dinu** [comment]
Hello, @JXH-SHU,

There is currently no way of doing so. Let's mark this as an enhancement.

Thank you!

**Comment by JXH-SHU** [comment]
Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexandru-dinu/cae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexandru-dinu/cae] How to control the degree of image distortion and bitstream size in your code (#22)





 
Hello, @JXH-SHU,
 
There is currently no way of doing so. Let's mark this as an enhancement.
 
Thank you!
