### ISSUE TITLE
How I can get the compressed image only when save image ? , (not the original image and the compressed image)

### ISSUE THREAD

**Issue by amrk723** [alexandru-dinu/cae#25]

**Comment by alexandru-dinu** [comment]
Related to #19.

**Comment by alexandru-dinu** [comment]
Hello, @amrk723 

I have pushed some changes (ff75a69). 

Now you can run
```
python test.py --config ../configs/test.yaml
```
and in the experiment folder there will be dumped a file named `enc_<batch_idx>.pt` -- this is the encoded tensor.

Also, there's now `model.encode(x)` and `model.decode(x)`, so you can reconstruct the image by doing:
```
enc = torch.load('enc.pt')
dec = model.decode(enc)
```

This is work in progress, I will merge on master when I'm comfortable with how things look.

Thanks!
