### ISSUE TITLE
 train problem

### ISSUE THREAD

**Issue by tuqiangwang** [alexandru-dinu/cae#4]
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2247

**Comment by tuqiangwang** [comment]
done by myself

**Comment by alexandru-dinu** [comment]
Hello, @tuqiangwang. 

Do you mind elaborating the problem cause and your solution? It might help others dealing with the same issue.

Thank you!
